# Generated by Django 5.0.7 on 2025-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_roombooking_phone_alter_contactinquiry_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
