# Generated by Django 5.0.7 on 2025-03-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_feedback_email_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room - 10,000'), ('studio', 'Studio Room - 12,000'), ('4_sharing', '4 Sharing - 8,500'), ('twin', 'Twin Room - 9,500'), ('6_sharing', '6 Sharing - 7,500'), ('8_sharing', '8 Sharing - 6,500')], max_length=20),
        ),
    ]
